apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
    component: config
data:
  AIRFLOW__CORE__EXECUTOR: LocalKubernetesExecutor
  AIRFLOW__WEBSERVER__SECRET_KEY: 4rXQ6OjKM8pYq8OFN-g-8nkGtm8vANkIlcF1asz5ceI=
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE: /opt/airflow/pod_template_file.yml
