apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      hostname: airflow-webserver
      containers:
        - name: airflow-webserver
          image: docker.io/library/airflow:latest
          imagePullPolicy: Never
          command:
            - airflow
            - webserver
          ports:
            - name: webserver
              containerPort: 8793
          envFrom:
            - configMapRef:
                name: airflow-config
