apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
spec:
  selector:
    app: airflow
    component: webserver
  ports:
    - name: webserver
      protocol: TCP
      port: 8080
  type: NodePort
