apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-user
  labels:
    app: airflow
    component: user
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch", "create"]
