apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-user
  labels:
    app: airflow
    component: user
subjects:
  - kind: ServiceAccount
    name: airflow-user
roleRef:
  kind: Role
  name: airflow-user
  apiGroup: rbac.authorization.k8s.io
