apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: airflow-user
  labels:
    app: airflow
    component: user
  annotations:
    kubernetes.io/service-account.name: airflow-user
