apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  selector:
    app: airflow
    component: scheduler
  ports:
    - name: logs
      port: 8793
  type: ClusterIP
