apiVersion: v1
kind: Pod
metadata:
  name: airflow-worker
  labels:
    app: airflow
    component: worker
spec:
  serviceAccountName: airflow-user
  containers:
    - name: base # Airflow requires the name to be 'base'.
      image: docker.io/library/airflow:latest
      imagePullPolicy: Never
      # Since within itself workers run tasks locally,
      # we need to override the executor to LocalExecutor.
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
      envFrom:
        - configMapRef:
            name: airflow-config
  restartPolicy: Never
